import path from "node:path";
import type { Skill, SkillArtifact, SkillExecutionContext, SkillResult } from "../types";

export type ScaffoldModuleType = "library" | "react-component" | "node-cli";

export type ScaffoldModuleInput = {
  moduleName: string;
  moduleType: ScaffoldModuleType;
  targetDirectory: string;
};

export type ScaffoldModuleOutput = {
  moduleName: string;
  moduleType: ScaffoldModuleType;
  targetDirectory: string;
  moduleDirectory: string;
  createdFiles: string[];
};

type FilesystemAdapter = {
  ensureDir?: (directoryPath: string) => Promise<void> | void;
  ensureDirectory?: (directoryPath: string) => Promise<void> | void;
  mkdir?: (directoryPath: string) => Promise<void> | void;
  createDirectory?: (directoryPath: string) => Promise<void> | void;
  writeFile?: (filePath: string, content: string) => Promise<void> | void;
  writeTextFile?: (filePath: string, content: string) => Promise<void> | void;
  write?: (filePath: string, content: string) => Promise<void> | void;
};

const MODULE_TYPES: readonly ScaffoldModuleType[] = [
  "library",
  "react-component",
  "node-cli"
];

const moduleNamePattern = /^[A-Za-z][A-Za-z0-9_-]*$/;

function toPosixPath(input: string): string {
  return input.replaceAll("\\", "/");
}

function normalizeTargetDirectory(input: string): string {
  const trimmed = toPosixPath(input).trim();
  if (!trimmed) {
    throw new Error("targetDirectory must not be empty.");
  }

  const normalized = path.posix.normalize(trimmed);
  const segments = normalized.split("/").filter(Boolean);
  if (segments.some((segment) => segment === "..")) {
    throw new Error("targetDirectory must not contain parent traversal segments.");
  }

  return normalized === "." ? "." : normalized.replace(/\/+$/, "");
}

function normalizeModuleName(input: string): string {
  const moduleName = input.trim();
  if (!moduleNamePattern.test(moduleName)) {
    throw new Error(
      "moduleName must start with a letter and contain only letters, numbers, '_' or '-'."
    );
  }
  return moduleName;
}

function toPascalCase(moduleName: string): string {
  return moduleName
    .split(/[-_]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

function resolveFilesystemAdapter(context: SkillExecutionContext): FilesystemAdapter {
  const candidate = context.adapters.filesystem;
  if (!candidate || typeof candidate !== "object") {
    throw new Error("scaffold_module requires context.adapters.filesystem.");
  }
  return candidate as FilesystemAdapter;
}

async function ensureDirectory(
  adapter: FilesystemAdapter,
  directoryPath: string
): Promise<void> {
  const method =
    adapter.ensureDir ??
    adapter.ensureDirectory ??
    adapter.mkdir ??
    adapter.createDirectory;

  if (!method) {
    throw new Error(
      "filesystem adapter must provide ensureDir/ensureDirectory/mkdir/createDirectory."
    );
  }

  await Promise.resolve(method(directoryPath));
}

async function writeFile(
  adapter: FilesystemAdapter,
  filePath: string,
  content: string
): Promise<void> {
  const method = adapter.writeFile ?? adapter.writeTextFile ?? adapter.write;
  if (!method) {
    throw new Error("filesystem adapter must provide writeFile/writeTextFile/write.");
  }

  await Promise.resolve(method(filePath, content));
}

function buildFiles(
  moduleName: string,
  moduleType: ScaffoldModuleType,
  moduleDirectory: string
): Array<{ path: string; content: string; artifactType: string }> {
  const packageJson = JSON.stringify(
    {
      name: moduleName,
      version: "0.1.0",
      private: true,
      type: "module",
      scripts: {
        build: "tsc --project tsconfig.json",
        test: "tsx --test test/*.test.ts"
      }
    },
    null,
    2
  );

  const symbolName = toPascalCase(moduleName);
  const fileRows: Array<{ path: string; content: string; artifactType: string }> = [
    {
      path: path.posix.join(moduleDirectory, "package.json"),
      content: `${packageJson}\n`,
      artifactType: "config"
    },
    {
      path: path.posix.join(moduleDirectory, "README.md"),
      content: `# ${moduleName}\n\nGenerated by scaffold_module (${moduleType}).\n`,
      artifactType: "markdown"
    }
  ];

  if (moduleType === "library") {
    fileRows.push({
      path: path.posix.join(moduleDirectory, "src", "index.ts"),
      content: `export function ${symbolName}(): string {\n  return "${moduleName}";\n}\n`,
      artifactType: "typescript"
    });
    return fileRows;
  }

  if (moduleType === "react-component") {
    fileRows.push(
      {
        path: path.posix.join(moduleDirectory, "src", `${symbolName}.tsx`),
        content:
          `type ${symbolName}Props = {\n  title?: string;\n};\n\n` +
          `export function ${symbolName}({ title = "${symbolName}" }: ${symbolName}Props) {\n` +
          "  return <section>{title}</section>;\n}\n",
        artifactType: "typescript"
      },
      {
        path: path.posix.join(moduleDirectory, "src", "index.ts"),
        content: `export * from "./${symbolName}";\n`,
        artifactType: "typescript"
      }
    );
    return fileRows;
  }

  fileRows.push(
    {
      path: path.posix.join(moduleDirectory, "src", "index.ts"),
      content:
        `export function run${symbolName}Cli(argv: string[]): number {\n` +
        `  if (argv.includes("--help")) {\n` +
        `    console.log("Usage: ${moduleName} [--help]");\n` +
        "  }\n" +
        "  return 0;\n}\n",
      artifactType: "typescript"
    },
    {
      path: path.posix.join(moduleDirectory, "bin", `${moduleName}.ts`),
      content:
        `#!/usr/bin/env node\nimport { run${symbolName}Cli } from "../src/index";\n\n` +
        `process.exitCode = run${symbolName}Cli(process.argv.slice(2));\n`,
      artifactType: "typescript"
    }
  );

  return fileRows;
}

export const scaffoldModuleSkill: Skill<ScaffoldModuleInput, ScaffoldModuleOutput> = {
  name: "scaffold_module",
  version: "1.0.0",
  description:
    "Create a new module directory with boilerplate files using the filesystem adapter.",
  inputSchema: {
    type: "object",
    additionalProperties: false,
    required: ["moduleName", "moduleType", "targetDirectory"],
    properties: {
      moduleName: {
        type: "string",
        minLength: 1,
        description: "Module folder/package name."
      },
      moduleType: {
        type: "string",
        enum: [...MODULE_TYPES],
        description: "Boilerplate profile to scaffold."
      },
      targetDirectory: {
        type: "string",
        minLength: 1,
        description: "Directory where the module folder should be created."
      }
    }
  },
  async execute(
    input: ScaffoldModuleInput,
    context: SkillExecutionContext
  ): Promise<SkillResult<ScaffoldModuleOutput>> {
    const moduleName = normalizeModuleName(input.moduleName);
    const moduleType = input.moduleType;
    if (!MODULE_TYPES.includes(moduleType)) {
      throw new Error(`moduleType must be one of: ${MODULE_TYPES.join(", ")}.`);
    }
    const targetDirectory = normalizeTargetDirectory(input.targetDirectory);

    const moduleDirectory =
      targetDirectory === "."
        ? moduleName
        : path.posix.join(targetDirectory, moduleName);

    const adapter = resolveFilesystemAdapter(context);
    const fileRows = buildFiles(moduleName, moduleType, moduleDirectory);
    const directories = new Set<string>([
      moduleDirectory,
      ...fileRows.map((row) => path.posix.dirname(row.path))
    ]);

    for (const directoryPath of directories) {
      await ensureDirectory(adapter, directoryPath);
    }

    for (const row of fileRows) {
      await writeFile(adapter, row.path, row.content);
    }

    const artifacts: SkillArtifact[] = fileRows.map((row) => ({
      path: row.path,
      artifactType: row.artifactType,
      metadata: {
        module_name: moduleName,
        module_type: moduleType
      }
    }));

    return {
      ok: true,
      output: {
        moduleName,
        moduleType,
        targetDirectory,
        moduleDirectory,
        createdFiles: fileRows.map((row) => row.path)
      },
      artifacts,
      events: [
        {
          type: "skill.scaffold_module.completed",
          level: "info",
          payload: {
            module_name: moduleName,
            module_type: moduleType,
            target_directory: targetDirectory,
            created_file_count: fileRows.length
          }
        }
      ]
    };
  }
};
