create table if not exists public.setup_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  integration_key text not null,
  status text not null check (status in ('not_configured', 'needs_auth', 'ready', 'error')),
  detail text
);

create table if not exists public.runs (
  id uuid primary key,
  created_at timestamptz not null default now(),
  section text not null,
  state text not null,
  payload jsonb not null default '{}'::jsonb
);

create table if not exists public.audit_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  actor text not null,
  action text not null,
  target text,
  metadata jsonb not null default '{}'::jsonb
);
