create extension if not exists pgcrypto;

create table if not exists public.salvo_workspaces (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  local_path text not null,
  description text,
  created_at timestamptz not null default now()
);

create table if not exists public.salvo_tasks (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.salvo_workspaces(id),
  title text not null,
  original_request text not null,
  normalized_request text not null,
  status text not null check (status in ('queued','planning','running','blocked','completed','failed','needs_review','cancelled')),
  requires_approval boolean not null default false,
  approved_at timestamptz,
  cancelled_at timestamptz,
  claimed_by text,
  claimed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.salvo_contracts (
  id uuid primary key default gen_random_uuid(),
  task_id uuid not null references public.salvo_tasks(id),
  version integer not null default 1,
  status text not null check (status in ('draft','approved','active','superseded','closed')),
  risk text not null check (risk in ('low','medium','high')),
  contract_json jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (task_id, version)
);

create table if not exists public.salvo_runs (
  id uuid primary key default gen_random_uuid(),
  task_id uuid not null references public.salvo_tasks(id),
  contract_id uuid not null references public.salvo_contracts(id),
  attempt_no integer not null default 1,
  agent_profile text not null,
  status text not null check (status in ('created','provisioning','starting','running','evaluating','completed','failed','blocked','cancelled')),
  worker_id text,
  runner_pid integer,
  heartbeat_at timestamptz,
  started_at timestamptz,
  ended_at timestamptz,
  exit_reason text,
  outcome_summary text,
  score integer,
  synthesized_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (task_id, attempt_no)
);

create table if not exists public.salvo_run_events (
  id bigint generated by default as identity primary key,
  run_id uuid not null references public.salvo_runs(id),
  sequence_no integer not null,
  event_type text not null,
  level text not null,
  payload_json jsonb not null default '{}'::jsonb,
  schema_version integer not null default 1,
  created_at timestamptz not null default now(),
  unique (run_id, sequence_no)
);

create table if not exists public.salvo_artifacts (
  id uuid primary key default gen_random_uuid(),
  run_id uuid not null references public.salvo_runs(id),
  task_id uuid not null references public.salvo_tasks(id),
  artifact_type text not null,
  path text not null,
  metadata_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.salvo_evaluations (
  id uuid primary key default gen_random_uuid(),
  run_id uuid not null unique references public.salvo_runs(id),
  contract_id uuid not null references public.salvo_contracts(id),
  passed boolean not null,
  score integer not null,
  outcome text not null,
  hard_fail_reason text,
  findings_json jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.salvo_research_documents (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.salvo_workspaces(id),
  title text not null,
  topic text not null,
  body_markdown text not null,
  source_run_ids uuid[] not null,
  confidence numeric(3,2) not null check (confidence >= 0 and confidence <= 1),
  review_status text not null check (review_status in ('unreviewed','accepted','rejected')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.salvo_memories (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.salvo_workspaces(id),
  source_run_ids uuid[] not null,
  memory_type text not null,
  title text not null,
  summary text not null,
  body_markdown text not null,
  tags text[] not null default '{}',
  confidence numeric(3,2) not null check (confidence >= 0 and confidence <= 1),
  review_status text not null check (review_status in ('unreviewed','accepted','rejected')),
  created_at timestamptz not null default now()
);

create index if not exists idx_salvo_tasks_claim
  on public.salvo_tasks (status, requires_approval, approved_at, created_at)
  where status = 'queued';

create index if not exists idx_salvo_runs_status_heartbeat
  on public.salvo_runs (status, heartbeat_at);

create index if not exists idx_salvo_run_events_run_sequence
  on public.salvo_run_events (run_id, sequence_no);

create index if not exists idx_salvo_runs_unsynthesized
  on public.salvo_runs (status, synthesized_at)
  where status in ('completed','failed','blocked') and synthesized_at is null;

create or replace function public.salvo_touch_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create or replace function public.salvo_prevent_terminal_run_status_change()
returns trigger as $$
begin
  if old.status in ('completed','failed','blocked','cancelled') and new.status <> old.status then
    raise exception 'Terminal runs are immutable: cannot transition % -> %', old.status, new.status;
  end if;
  return new;
end;
$$ language plpgsql;

create or replace function public.salvo_forbid_event_mutation()
returns trigger as $$
begin
  raise exception 'salvo_run_events is append-only';
end;
$$ language plpgsql;

drop trigger if exists trg_salvo_tasks_touch_updated_at on public.salvo_tasks;
create trigger trg_salvo_tasks_touch_updated_at
before update on public.salvo_tasks
for each row execute function public.salvo_touch_updated_at();

drop trigger if exists trg_salvo_contracts_touch_updated_at on public.salvo_contracts;
create trigger trg_salvo_contracts_touch_updated_at
before update on public.salvo_contracts
for each row execute function public.salvo_touch_updated_at();

drop trigger if exists trg_salvo_runs_touch_updated_at on public.salvo_runs;
create trigger trg_salvo_runs_touch_updated_at
before update on public.salvo_runs
for each row execute function public.salvo_touch_updated_at();

drop trigger if exists trg_salvo_research_touch_updated_at on public.salvo_research_documents;
create trigger trg_salvo_research_touch_updated_at
before update on public.salvo_research_documents
for each row execute function public.salvo_touch_updated_at();

drop trigger if exists trg_salvo_runs_terminal_guard on public.salvo_runs;
create trigger trg_salvo_runs_terminal_guard
before update on public.salvo_runs
for each row execute function public.salvo_prevent_terminal_run_status_change();

drop trigger if exists trg_salvo_run_events_no_update on public.salvo_run_events;
create trigger trg_salvo_run_events_no_update
before update on public.salvo_run_events
for each row execute function public.salvo_forbid_event_mutation();

drop trigger if exists trg_salvo_run_events_no_delete on public.salvo_run_events;
create trigger trg_salvo_run_events_no_delete
before delete on public.salvo_run_events
for each row execute function public.salvo_forbid_event_mutation();
