create table if not exists public.salvo_task_chat_sessions (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.salvo_workspaces(id) on delete cascade,
  status text not null default 'active' check (status in ('active', 'approved')),
  pending_proposal_json jsonb,
  approved_task_id uuid references public.salvo_tasks(id) on delete set null,
  approved_contract_id uuid references public.salvo_contracts(id) on delete set null,
  approved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.salvo_task_chat_messages (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.salvo_task_chat_sessions(id) on delete cascade,
  role text not null check (role in ('user', 'assistant')),
  message_text text not null,
  proposed_contract_json jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_salvo_task_chat_sessions_workspace_created
  on public.salvo_task_chat_sessions (workspace_id, created_at desc);

create index if not exists idx_salvo_task_chat_messages_session_created
  on public.salvo_task_chat_messages (session_id, id asc);

drop trigger if exists trg_salvo_task_chat_sessions_touch_updated_at on public.salvo_task_chat_sessions;
create trigger trg_salvo_task_chat_sessions_touch_updated_at
before update on public.salvo_task_chat_sessions
for each row execute function public.salvo_touch_updated_at();
